### ISSUE TITLE
Uncaught ReferenceError: light is not defined

### ISSUE THREAD

**Issue by drpowell** [themadcreator/seen#10]
Since coffeescript 1.9.0, arguments with "@" are no-longer accessible by the bare name.  

One problem I found in `seen.LightRenderModel` that uses `@light` in the argument list cannot be used as `light` in the constructor body.

From the coffeescript changelog:
Changed strategy for the generation of internal compiler variable names. Note that this means that @example function parameters are no longer available as naked example variables within the function body.

**Comment by themadcreator** [comment]
Thanks for reporting this. It will be fixed in the next version.

**Comment by themadcreator** [comment]
released.
