### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by JikkuJose** [themadcreator/seen#15]
Any chance you are planning to release it as an npm package?

**Comment by themadcreator** [comment]
Oh yes, I would like to publish one. I think the best would be to export the Seen namespace without any minification since most project have a post minification step and usage via npm implies it will be imported into a larger project.

Does that sound reasonable?

**Comment by JikkuJose** [comment]
Frankly, I am just getting started with Javascript itself. NPM seemed to be the best place to start as I am so used to Ruby gems.

But, from the limited exposure, your rationale seems sensible. Have also read somewhere about module loaders than can load only specific modules, I guess you will require non-minified code to utilize it.

**Comment by delta1** [comment]
Hi @themadcreator I'm busy hacking on this to submit a PR so this can be published to NPM, just wondering if you have preferences for a [.editorconfig](http://editorconfig.org/) since there is none defined ? How about [this gist](https://gist.github.com/delta1/3e8b1ab3d0ca0631f1532ec1b77eda07)?

**Comment by delta1** [comment]
Please see #16

**Comment by themadcreator** [comment]
https://www.npmjs.com/package/seen-js

**Comment by themadcreator** [comment]
update: https://www.npmjs.com/package/seen

**Comment by delta1** [comment]
You managed to grab that namespace from the squatter? Nice! :)

**Comment by JikkuJose** [comment]
Wow! So, I can just do `require('seen')`?

**Comment by themadcreator** [comment]
Yeah sort of. He's still listed as a "contributor", but whatever.

Yeah, `require('seen')` is all you need =)
