### ISSUE TITLE
Line between the surfaces

### ISSUE THREAD

**Issue by screendle** [themadcreator/seen#20]
Hello! Is there a way to remove the line between the surfaces?
![surf](https://cloud.githubusercontent.com/assets/18581906/15633980/f94b7508-25c1-11e6-877b-88f8375403e5.png)

**Comment by themadcreator** [comment]
Sadly there is no way to remove this line. It is an artifact of the polygon rendering algorithm used by the browser. The anti-aliasing of the edges creates a partially transparent gap between polygons. This is a very low-level rendering artifact that I can't control.

However, one work-around solution that might work for you is to add a material to the shape's stroke with the same color as the fill. See [the stroke method](http://seenjs.io/docco/seen.html#section-190) on seen.Shape

**Comment by screendle** [comment]
Thank you! Тhe stroke method to help me.
