### ISSUE TITLE
Not displayed upper surface of some shapes

### ISSUE THREAD

**Issue by screendle** [themadcreator/seen#21]
Why is not drawn from the upper surface of some figures obtained by extrude?  Is it possible to fix it?

Above:
![s1](https://cloud.githubusercontent.com/assets/18581906/15635136/25e7a29a-25df-11e6-93cb-2b34e7bb588c.png)
![s3](https://cloud.githubusercontent.com/assets/18581906/15635139/3444e30c-25df-11e6-922c-1cf6586aa979.png)
Below (here no problems):
![s2](https://cloud.githubusercontent.com/assets/18581906/15635138/2de626ba-25df-11e6-8cb6-e3bfdcf0ec18.png)
Piece of cake - no problem (above):
![s4](https://cloud.githubusercontent.com/assets/18581906/15635141/38f3ead8-25df-11e6-8133-bb0e2967cbc2.png)
Here is the code for the first shape (his based on the pipes code):

```
pie = (point1, point2, radius = 1, segments = 8) ->

	axis  = point2.copy().subtract(point1)
	perp  = axis.perpendicular().multiply(radius)
	theta = -Math.PI * 2.0 / segments
	quat  = seen.Quaternion.pointAngle(axis.copy().normalize(), theta).toMatrix()

	points = [0...segments - 80].map (i) ->
		p = point1.copy().add(perp)
		perp.transform(quat)
		return p

	points.push point1

	return seen.Shapes.extrude(points, axis)


shape = pie(seen.P(0, 0, 0), seen.P(0, 1, 0), 1, 200)
```

**Comment by themadcreator** [comment]
Thanks for the screenshots!

My guess is that the top shape's points are in a winding order that produces a normal facing away from the camera.

There are a couple solutions to this:
1) Turn off [backface culling](https://en.wikipedia.org/wiki/Back-face_culling). This will prevent seen.js from hiding the faces of polygons that have normals facing away from the camera. You can turn off backface culling on the individual surface [here](http://seenjs.io/docco/seen.html#section-184) or on the whole scene [here](http://seenjs.io/docco/seen.html#section-276).
2) Change how the initial surface is created to wind the points around the other way. I think you can do this just by negating your `theta` value.

**Comment by screendle** [comment]
Thanks!
