### ISSUE TITLE
Apply Material properties on new seen.Material

### ISSUE THREAD

**Issue by CKH4** [themadcreator/seen#22]
I would like to set specularity and metallic when creating a new material `new seen.Material`. How can I do this?

Also can you lock a rotation axis on a model?

**Comment by themadcreator** [comment]
Take a look at the docs for the constructor of `seen.Material`: http://seenjs.io/docco/seen.html#section-110

The second arguments is an options hash. You can pass in an object like:
```javascript
{
  metallic: true,
  specularExponent: 10
}
```

**Comment by themadcreator** [comment]
And, of course, you can play with those parameters in the materials gallery demo: http://seenjs.io/demo-material-gallery.html

**Comment by CKH4** [comment]
Thank you so much!
