### ISSUE TITLE
Please port seen.js to google Dart!

### ISSUE THREAD

**Issue by Emasoft** [themadcreator/seen#4]
I was searching for a 3D library that renders natively in SVG (not in canvas or WebGL), in a way that the DOM structure will be preserved at each frame and the texts are kept selectable and indexable by search engines. Also SVG is resolution and dpi independent, and stays sharp on retina displays and the like.
At the beginning I found three.js, but its renderer pipeline is raster on canvas. Then I tried snap.svg library, but it was 2D only. Finally I found your awesome library. Great work!

Being my project writted in Dart It would be ideal to have a Dart version of your 3D SVG engine. On browsers that support it, Dart runs natively and it is up to 4 times faster than javascript. On Chromium you'll probably get a huge performance improvement for your engine.

Do you think to make a Dart port of Seen in the future? Something like the Dart port of three.js, https://github.com/threeDart ?

**Comment by themadcreator** [comment]
Dart still hasn't arisen as a big player on the web tech scene. For the time being I don't intend to make this port, so I'm going to close this issue as wontfix.
