### ISSUE TITLE
Finish articulated skeleton model and add demo.

### ISSUE THREAD

**Issue by ctzurcanu** [themadcreator/seen#7]
I just found this lib and I was getting excited to see in the source something about joints for a human model. Any plans for a demo?

**Comment by themadcreator** [comment]
Yes, but unfortunately it didn't make it into the last release. It's next on the list, though.

**Comment by themadcreator** [comment]
I've just released version 2.5 including support for reading in a standard mocap format: BVH. 

Take a look at the demo: http://seenjs.io/demo-mocap.html

You can find tons of free bvh files here:
https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture/daz-friendly-release
Which are conversions of this huge database:
http://mocap.cs.cmu.edu/search.php
