### ISSUE TITLE
Simplex3D isn't included in seen.js

### ISSUE THREAD

**Issue by HorizonShadow** [themadcreator/seen#8]
Simply put, Simplex3D isn't included in seen.js. 

You can find Simplex3D defined [here](https://github.com/themadcreator/seen/blob/master/site/lib/simplex-noise.coffee). 

You can see it in use in a demo [here](http://seenjs.io/demo-noisy-patch.html)

And you can see it not being found [here](http://jsfiddle.net/bqjh6xLp/4/)

I understand Simplex3D isn't strictly a part of the library, but it's generally nice for people to be able to copy and paste demo code so they can play around with it.

**Comment by themadcreator** [comment]
added to 0.2.4 as seen.Simplex3D
