### ISSUE TITLE
Chrome thinks seen.min.js could be dangerous

### ISSUE THREAD

**Issue by lflee** [themadcreator/seen#9]
I tried to download http://seenjs.io/dist/latest/seen.min.js , Chrome shows "seen.min.js is not commonly downloaded and could be dangerous".

Would you resolve it with Chrome - https://support.google.com/webmasters/answer/3258249 ?

**Comment by themadcreator** [comment]
Thanks for letting me know, I'll investigate.

**Comment by themadcreator** [comment]
I'm registered the site as my property with google. They detect no malware on the domain. Could you please check again and confirm that the warning is gone?

**Comment by lflee** [comment]
Yeah, it's fixed. Thanks!
